# Generated by Django 3.2.18 on 2023-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('bid_price', models.FloatField()),
                ('ask_price', models.FloatField()),
                ('exchange_rate', models.FloatField()),
            ],
        ),
    ]
