# Generated by Django 3.2.18 on 2023-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexData_Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
            ],
            options={
                'db_table': 'api_forexdata_weekly',
            },
        ),
        migrations.DeleteModel(
            name='ForexData_Monthly',
        ),
    ]
