# Generated by Django 3.2.18 on 2023-04-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly', '0003_rename_forexdata_weekly_forexdata_monthly'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forexdata_monthly',
            table='api_forexdata_monthly',
        ),
    ]
